FROM golang:1.8

#RUN curl -s https://packagecloud.io/install/repositories/phalcon/nightly/script.deb.sh | sudo bash
#RUN apt-get update
#RUN apt-get install -y php7.0-phalcon

#WORKDIR /root
#RUN rm -rf /usr/bin/phalcon
#RUN git clone git://github.com/phalcon/phalcon-devtools.git /root/phalcon-devtools
#RUN ln -s /root/phalcon-devtools/phalcon.php /usr/bin/phalcon
#RUN chmod ugo+x /usr/bin/phalcon

#RUN curl -sS https://getcomposer.org/installer | php
#RUN mv composer.phar /usr/local/bin/composer
#RUN chmod +x /usr/local/bin/composer

#RUN openssl genrsa -out private.key 1024
#RUN openssl rsa -in private.key -pubout -out public.key

#RUN echo "xdebug.remote_autostart=on" >> /etc/php/7.0/fpm/conf.d/20-xdebug.ini
#RUN echo "extension=mongo.so" >> /etc/php/7.0/fpm/php.ini
#RUN echo "nameserver 8.8.8.8" >> /etc/resolv.conf
#RUN cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
#
#RUN apt-get install -y nodejs
#RUN apt-get install -y npm
#RUN npm install pm2 -g
#
#WORKDIR /app
#
#RUN ln -fs /usr/bin/nodejs /usr/local/bin/node

#CMD pm2 start
#CMD bash

#WORKDIR /go/src/app
#COPY . /go/src/app

#RUN go-wrapper download
# "go get -d -v ./..."
#RUN go-wrapper install
# "go install -v ./..."

#CMD ["go-wrapper", "run"]
# ["app"]

RUN curl https://glide.sh/get | sh

WORKDIR /go/src/app
RUN glide -y init

RUN go get github.com/astaxie/beego
RUN go get github.com/beego/bee
RUN go get gopkg.in/mgo.v2

RUN go get gopkg.in/mgo.v2/bson
RUN go get github.com/astaxie/beego
RUN go install github.com/astaxie/beego
