version: "2"
services:
#    nginx:
#        image: phalconphp/nginx
#        container_name: vkbot_nginx
#        ports:
#            - "7000:80"
#        volumes:
#            - ../app:/app
#            - ./nginx/default.conf:/etc/nginx/sites-available/default.conf
#            - ./nginx/default.conf:/etc/nginx/sites-enabled/default.conf
#        depends_on:
#            - php
#    php:
#        build:
#            context: ./phalcon
#            dockerfile: Dockerfile
#        entrypoint: ""
#        command: bash -c "php-fpm7.0 -F"
#        labels:
#            project.git: https://gitlab.com/bongrun/vkbot.git
#        container_name: vkbot_phalcon
#        working_dir: /app
##        ports:
##            - "12000:9000"
##            - "13000:9001"
#        volumes:
#            - ../app:/app
#        depends_on:
#            - gochat_mongo
#            - gochat_rabbitmq
#        links:
#            - gochat_mongo
#            - gochat_rabbitmq
#        dns: 8.8.8.8
#    pm2:
#        build:
#            context: ./pm2
#            dockerfile: Dockerfile
#        entrypoint: ""
#        command: bash -c "pm2 start public/cli.php --interpreter=php && pm2 logs"
#        working_dir: /app
#        volumes:
#            - ../app:/app
#        depends_on:
#            - php
#        links:
#            - php
#        dns: 8.8.8.8
    gochat_go:
        build:
            context: ./go
            dockerfile: Dockerfile
#        image: golang:1.8
        container_name: gochat_go
        volumes:
            - ../back:/go/src/gochat/back
        working_dir: /go/src/gochat/back
        ports:
            - 9005:8080
#        command: tail -f /etc/hosts
#        command: go run main.go
#        command: glide update
#        command: glide install
        command: bash -c "glide update && bee run"
    gochat_mongodata:
        image: mongo:3.0.4
        container_name: gochat_mongodata
        volumes:
            - gochat-mongo:/data/db
        command: --break-mongo
    gochat_mongo:
        image: mongo:latest
        container_name: gochat_mongo
        volumes_from:
            - gochat_mongodata
        ports:
          - 27017:27017
        command: --smallfiles --rest
    gochat_rabbitmq:
        image: 'rabbitmq:3-management'
        hostname: gochat_rabbitmq_hn
        container_name: gochat_rabbitmq
        ports:
            - 9900:15672
        volumes:
            - gochat-rabbitmq:/var/lib/rabbitmq

volumes:
  gochat-redis:
  gochat-rabbitmq:
  gochat-mongo: